bitbag_admin_block:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin/block.yml"

bitbag_admin_page:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin/page.yml"

bitbag_admin_frequently_asked_question:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin/frequently_asked_question.yml"

bitbag_admin_section:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin/section.yml"

bitbag_admin_ajax_generate_page_slug:
    path: /page/generate-slug
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page_slug:generateAction