sylius_grid:
    grids:
        bitbag_admin_frequently_asked_question:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.frequently_asked_question.class%"
                    repository:
                        method: createListQueryBuilder
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: code
                question:
                    type: string
                    label: bitbag_cms.ui.question
                    sortable: name
                answer:
                    type: string
                    label: bitbag_cms.ui.answer
                    sortable: name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete