sylius_grid:
    grids:
        bitbag_cms_admin_page:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.page.class%"
                    repository:
                        method: createListQueryBuilder
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                slug:
                    type: string
                    label: sylius.ui.slug
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name, slug]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            sorting:
                code: asc
