sylius_grid:
    grids:
        bitbag_admin_cms_plugin_page:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.page.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: code
                name:
                    type: string
                    label: sylius.ui.type
                    sortable: name
                name:
                    type: string
                    label: sylius.ui.type
                    sortable: name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, type]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete