services:
    bitbag_sylius_cms_plugin.controller.page_slug:
        class: BitBag\SyliusCmsPlugin\Controller\PageSlugController
        arguments:
            - "@sylius.generator.slug"

    bitbag_sylius_cms_plugin.controller.action.admin.product_search:
        class: BitBag\SyliusCmsPlugin\Controller\Action\Admin\ProductSearchAction
        arguments:
            - "@bitbag_sylius_cms_plugin.repository.product"
            - "@fos_rest.view_handler.default"
