services:
    bitbag.custom_factory.block:
        class: BitBag\CmsPlugin\Factory\BlockFactory
        decorates: "bitbag.factory.block"
        public: false
        decoration_priority: 1
        arguments:
            - "@bitbag.custom_factory.block.inner"