services:
    bitbag_sylius_cms_plugin.provider.media.image:
        class: BitBag\SyliusCmsPlugin\Media\Provider\ImageProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@templating.engine.twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/image.html.twig"
            - "web/media/image"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: image, label: bitbag_sylius_cms_plugin.ui.image_provider }

    bitbag_sylius_cms_plugin.provider.media.video:
        class: BitBag\SyliusCmsPlugin\Media\Provider\VideoProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@templating.engine.twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/video.html.twig"
            - "web/media/video"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: video, label: bitbag_sylius_cms_plugin.ui.video_provider }

    bitbag_sylius_cms_plugin.provider.media.file:
        class: BitBag\SyliusCmsPlugin\Media\Provider\FileProvider
        arguments:
            - "@bitbag_sylius_cms_plugin.media_uploader"
            - "@templating.engine.twig"
            - "@@BitBagSyliusCmsPlugin/Shop/Media/Show/file.html.twig"
            - "web/media/file"
        tags:
            - { name: bitbag_sylius_cms_plugin.media_provider, type: file, label: bitbag_sylius_cms_plugin.ui.file_provider }
