services:
    bitbag.twig.extension.block:
        class: BitBag\CmsPlugin\Twig\Extension\RenderBlockExtension
        public: false
        arguments:
            - "@bitbag.repository.block"
            - "@logger"
        tags:
            - { name: twig.extension }

    bitbag.twig.extension.page_link_by_code:
        class: BitBag\CmsPlugin\Twig\Extension\RenderPageLinkByCodeExtension
        public: false
        arguments:
            - "@bitbag.repository.page"
            - "@logger"
        tags:
            - { name: twig.extension }