services:
    bitbag.twig.extension.block:
        class: BitBag\SyliusCmsPlugin\Twig\Extension\RenderBlockExtension
        public: false
        arguments:
            - "@bitbag.repository.block"
            - "@bitbag.resolver.block_template"
            - "@bitbag.resolver.block_resource"
        tags:
            - { name: twig.extension }