sylius_resource:
    resources:
        bitbag.frequently_asked_question:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestion
                form: BitBag\SyliusCmsPlugin\Form\Type\FrequentlyAskedQuestionType
                repository: BitBag\SyliusCmsPlugin\Repository\FrequentlyAskedQuestionRepository
            translation:
                classes:
                    model: BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestionTranslation