sylius_resource:
    resources:
        bitbag.page:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\Page
                form: BitBag\SyliusCmsPlugin\Form\Type\PageType
                repository: BitBag\SyliusCmsPlugin\Repository\PageRepository
                controller: BitBag\SyliusCmsPlugin\Controller\PageController
            translation:
                classes:
                    model: BitBag\SyliusCmsPlugin\Entity\PageTranslation