sylius_resource:
    resources:
        bitbag.section:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\Section
                form: BitBag\SyliusCmsPlugin\Form\Type\SectionType
                repository: BitBag\SyliusCmsPlugin\Repository\SectionRepository
            translation:
                classes:
                    model: BitBag\SyliusCmsPlugin\Entity\SectionTranslation