imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/sylius_resource.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/grids.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/services.yml" }

jms_serializer:
    metadata:
        directories:
            bitbag-section:
                namespace_prefix: "BitBag\\SyliusCmsPlugin"
                path: "@BitBagSyliusCmsPlugin/Resources/config/serializer"
