imports:
    - { resource: "@BitBagCmsPlugin/Resources/config/sylius_resource.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/grids.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/services.yml" }