services:
    bitbag.cms_plugin.form.type.block:
        class: BitBag\CmsPlugin\Form\Type\BlockType
        arguments: ['%bitbag.model.block.class%', ['bitbag']]
        tags:
            - { name: form.type }

    bitbag.cms_plugin.form.type.translation.text:
        class: BitBag\CmsPlugin\Form\Type\Translation\TextTranslationType
        arguments: ['%bitbag.model.block_translation.class%', ['bitbag']]
        tags:
            - { name: form.type }

    bitbag.cms_plugin.form.type.translation.image:
        class: BitBag\CmsPlugin\Form\Type\Translation\ImageTranslationType
        arguments: ['%bitbag.model.block_translation.class%', ['bitbag']]
        tags:
            - { name: form.type }

    bitbag.cms_plugin.form.type.image:
        class: BitBag\CmsPlugin\Form\Type\ImageType
        arguments: ['BitBag\CmsPlugin\Entity\Image', ['bitbag']]
        tags:
            - { name: form.type }