services:
    bitbag.cms_plugin.form.type.block:
        class: BitBag\CmsPlugin\Form\Type\BlockType
        tags:
            - { name: form.type }
        arguments: ['%bitbag.model.block.class%', ['bitbag']]

    bitbag.cms_plugin.form.type.translation.text:
        class: BitBag\CmsPlugin\Form\Type\Translation\TextTranslationType
        tags:
            - { name: form.type }
        arguments: ['%bitbag.model.block_translation.class%', ['bitbag']]

    bitbag.cms_plugin.form.type.translation.image:
        class: BitBag\CmsPlugin\Form\Type\Translation\ImageTranslationType
        tags:
            - { name: form.type }
        arguments: ['%bitbag.model.block_translation.class%', ['bitbag']]

    bitbag.cms_plugin.form.type.block_image:
        class: BitBag\CmsPlugin\Form\Type\BlockImageType
        tags:
            - { name: form.type }
        arguments: ['BitBag\CmsPlugin\Entity\BlockImage', ['bitbag']]