imports:
    - { resource: "@BitBagCmsPlugin/Resources/config/grids/admin.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/grids/shop.yml" }

sylius_grid:
    templates:
        action:
            create_block: "@BitBagCmsPlugin/Block/Action/_create.html.twig"