imports:
    - { resource: "@BitBagCmsPlugin/Resources/config/grids/block.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/grids/page.yml" }

sylius_grid:
    templates:
        action:
            create_block: "@BitBagCmsPlugin/Block/Action/_create.html.twig"