imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/grids/admin.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/grids/shop.yml" }

sylius_grid:
    templates:
        action:
            create_block: "@BitBagSyliusCmsPlugin/Grid/Action/createBlock.html.twig"
            import: "@BitBagSyliusCmsPlugin/Grid/Action/import.html.twig"
