imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/grids/admin.yml" }
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/grids/shop.yml" }

sylius_grid:
    templates:
        action:
            create_block: "@BitBagSyliusCmsPlugin/Block/Action/_create.html.twig"
            import: "@BitBagSyliusCmsPlugin/"
