bitbag_admin_cms_plugin_block:
    resource: "@BitBagCmsPlugin/Resources/config/routing/block.yml"
    prefix: /admin

bitbag_admin_cms_plugin_page:
    resource: "@BitBagCmsPlugin/Resources/config/routing/page.yml"
    prefix: /admin

bitbag_cms_plugin_show_action:
    path: /page/{slug}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.page:showAction
        _sylius:
            template: BitBagCmsPlugin:Page:show.html.twig
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()" #TODO
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug