imports:
    - { resource: services/twig.yml }
    - { resource: services/form.yml }
    - { resource: services/factory.yml }
    - { resource: services/event_listener.yml }
    - { resource: services/controller.yml }
    - { resource: services/fixture.yml }
    - { resource: services/repository.yml }
    - { resource: services/importer.yml }
    - { resource: services/resolver.yml }

services:
    bitbag_sylius_cms_plugin.resolver.block_resource:
        class: BitBag\SyliusCmsPlugin\Resolver\BlockResourceResolver
        arguments:
            - "@bitbag_sylius_cms_plugin.repository.block"
            - "@logger"
            - "@sylius.context.channel"

    bitbag_sylius_cms_plugin.resolver.page_resource:
        class: BitBag\SyliusCmsPlugin\Resolver\PageResourceResolver
        arguments:
            - "@bitbag_sylius_cms_plugin.repository.page"
            - "@sylius.context.locale"
            - "@logger"

    bitbag_sylius_cms_plugin.resolver.block_template:
        class: BitBag\SyliusCmsPlugin\Resolver\BlockTemplateResolver

    bitbag_sylius_cms_plugin.reader.csv:
        class: BitBag\SyliusCmsPlugin\Reader\CsvReader

    bitbag_sylius_cms_plugin.processor.import:
        class: BitBag\SyliusCmsPlugin\Processor\ImportProcessor
        arguments:
            - "@bitbag_sylius_cms_plugin.importer.chain"
            - "@bitbag_sylius_cms_plugin.reader.csv"
            - "@doctrine.orm.entity_manager"

    bitbag_sylius_cms_plugin.command.import_from_csv:
        class: BitBag\SyliusCmsPlugin\Command\ImportFromCsvCommand
        arguments:
            - "@bitbag_sylius_cms_plugin.processor.import"
        tags:
            - { name: console.command }

    bitbag_sylius_cms_plugin.downloader.image:
        class: BitBag\SyliusCmsPlugin\Downloader\ImageDownloader
        arguments:
            - "@filesystem"
