imports:
    - { resource: "@BitBagCmsPlugin/Resources/config/sylius_resource/block.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/sylius_resource/page.yml" }
    - { resource: "@BitBagCmsPlugin/Resources/config/sylius_resource/frequently_asked_question.yml" }