services:
    bitbag.cms_plugin.twig.extension.block:
        class: BitBag\CmsPlugin\Twig\Extension\BlockExtension
        public: false
        arguments:
            - '@bitbag.repository.block'
            - '@logger'

        tags:
            - { name: twig.extension }

    bitbag.cms_plugin.twig.extension.page_link_by_code:
        class: BitBag\CmsPlugin\Twig\Extension\PageLinkByCodeExtension
        public: false
        arguments:
            - '@bitbag.repository.page'
            - '@logger'

        tags:
            - { name: twig.extension }