services:
    bitbag.cms_plugin.twig_extension.block:
        class: BitBag\CmsPlugin\Twig\Extension\BlockExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ['@bitbag.cms_plugin.templating_helper.block']