bitbag_shop_page_show:
    path: /faq
    methods: [GET]
    defaults:
        _controller: bitbag.controller.frequently_asked_question:indexAction
        _sylius:
            template: BitBagCmsPlugin:Shop/FrequentlyAskedQuestion:index.html.twig
            repository:
                method: findEnabledOrderedByPosition
                arguments:
                    - "expr:service('sylius.context.locale').getLocaleCode()"