bitbag_shop_section_show:
    path: /section/{code}
    methods: [GET]
    defaults:
        _controller: bitbag.controller.section:showAction
        _sylius:
            template: $template
            repository:
                method: findOneByCode
                arguments:
                    - $code
