bitbag_sylius_cms_plugin_shop_section_show:
    path: /section/{code}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.section:showAction
        _sylius:
            template: $template
            repository:
                method: findOneByCodeAndChannelCode
                arguments:
                    - $code
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - "expr:service('sylius.context.channel').getChannel().getCode()"
