BitBag\CmsPlugin\Entity\BlockTranslation:
    properties:
        image:
            - Valid: ~
        name:
            - Length:
                min: 2
                max: 250
                minMessage: bitbag.block.name.min_length
                maxMessage: bitbag.block.name.max_length
                groups: [bitbag]
        content:
            - Length:
                min: 2
                minMessage: bitbag.block.content.min_length
                groups: [bitbag]