BitBag\CmsPlugin\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [code]
            groups: ['bitbag']
            message: 'bitbag.cms.page.code.unique'
    properties:
        code:
            - NotBlank: { message: 'bitbag.cms.page.code.not_blank', groups: ['bitbag'] }
            - Length:
                min: 2
                max: 250
                minMessage: 'bitbag.cms.page.code.min_length'
                maxMessage: 'bitbag.cms.page.code.max_length'
                groups: ['bitbag']
        translations:
            - Valid: ~