sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.media:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\Media
                form: BitBag\SyliusCmsPlugin\Form\Type\MediaType
