bitbag_admin_section:
    resource: |
        alias: bitbag.section
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: bitbag_admin_section
        except: ['show']
        permission: true
        vars:
            all:
                header: bitbag.ui.sections_header
                subheader: bitbag.ui.sections_subheader
                templates:
                    form: BitBagCmsPlugin:Section:Crud/_form.html.twig
            index:
                icon: grid layout
    type: sylius.resource

bitbag_admin_ajax_section_by_name_phrase:
    path: /ajax/sections/search
    methods: [GET]
    defaults:
        _format: json
        _controller: bitbag.controller.section:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase
                    locale: expr:service('sylius.context.locale').getLocaleCode()

bitbag_admin_ajax_section_by_code:
    path: /ajax/sections/code
    methods: [GET]
    defaults:
        _format: json
        _controller: bitbag.controller.section:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]