BitBag\CmsPlugin\Entity\Block:
    type: entity
    table: bitbag_block
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 64
            unique: true
        type:
            type: string
            length: 64
        enabled:
            type: boolean
    manyToMany:
        sections:
            targetEntity: BitBag\CmsPlugin\Entity\Section
            joinTable:
                name: bitbag_block_sections
                joinColumns:
                    block_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    section_id:
                        referencedColumnName: id
                        onDelete: CASCADE