BitBag\SyliusCmsPlugin\Entity\BlockTranslation:
    type: entity
    table: bitbag_cms_block_translation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            nullable: true
        content:
            column: content
            type: text
            nullable: true
        link:
            column: link
            type: text
            nullable: true
    oneToOne:
        image:
            targetEntity: BitBag\SyliusCmsPlugin\Entity\BlockImage
            mappedBy: owner
            cascade: [ALL]
            joinColumn:
                name: image_id
                referencedColumnName: id
