BitBag\CmsPlugin\Entity\FrequentlyAskedQuestion:
    type: entity
    table: bitbag_frequently_asked_question
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            nullable: false
        position:
            type: integer
            nullable: false
        enabled:
            type: boolean
            nullable: false
    manyToMany:
        sections:
            targetEntity: BitBag\CmsPlugin\Entity\Section
            joinTable:
                name: bitbag_frequently_asked_question_sections
                joinColumns:
                    block_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    section_id:
                        referencedColumnName: id
                        onDelete: CASCADE