BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestionTranslation:
    type: entity
    table: bitbag_sylius_cms_plugin_frequently_asked_question_translation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            column: question
            type: string
            length: 1500
            nullable: false
        answer:
            column: answer
            type: text
            nullable: false
