BitBag\CmsPlugin\Entity\FrequentlyAskedQuestion:
    type: entity
    table: bitbag_cms_frequently_asked_question
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
            nullable: false
        enabled:
            type: boolean
            nullable: false