BitBag\CmsPlugin\Entity\FrequentlyAskedQuestion:
    type: entity
    table: bitbag_frequently_asked_question
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            column: code
            type: string
            nullable: false
        position:
            column: position
            type: integer
            nullable: false
        enabled:
            column: enabled
            type: boolean
            nullable: false