BitBag\CmsPlugin\Entity\Image:
    type: entity
    table: bitbag_image
    oneToOne:
        owner:
            targetEntity: BitBag\CmsPlugin\Entity\BlockTranslation
            inversedBy: image
            cascade: [ALL]
            joinColumn:
                name: owner_id
                referencedColumnName: id