BitBag\CmsPlugin\Entity\Image:
    type: entity
    table: bitbag_cms_image
    oneToOne:
        owner:
            targetEntity: BitBag\CmsPlugin\Entity\BlockTranslation
            inversedBy: image
            joinColumn:
                name: owner_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false