BitBag\CmsPlugin\Entity\Page:
    type: entity
    table: bitbag_page
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 250
            unique: true
        enabled:
            type: boolean
    manyToMany:
        products:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            joinTable:
                name: bitbag_page_products
                joinColumns:
                    page_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE
        sections:
            targetEntity: BitBag\CmsPlugin\Entity\Section
            joinTable:
                name: bitbag_page_sections
                joinColumns:
                    block_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    section_id:
                        referencedColumnName: id
                        onDelete: CASCADE
