BitBag\CmsPlugin\Entity\SectionTranslation:
    type: entity
    table: bitbag_section_translation
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            nullable: true