BitBag\SyliusCmsPlugin\Entity\Section:
    type: entity
    table: bitbag_sylius_cms_plugin_section
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            column: code
            type: string
            length: 250
            unique: true
